/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Software } from "./Software";
import { SoftwareCountArgs } from "./SoftwareCountArgs";
import { SoftwareFindManyArgs } from "./SoftwareFindManyArgs";
import { SoftwareFindUniqueArgs } from "./SoftwareFindUniqueArgs";
import { DeleteSoftwareArgs } from "./DeleteSoftwareArgs";
import { SoftwareService } from "../software.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Software)
export class SoftwareResolverBase {
  constructor(
    protected readonly service: SoftwareService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Software",
    action: "read",
    possession: "any",
  })
  async _softwareItemsMeta(
    @graphql.Args() args: SoftwareCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Software])
  @nestAccessControl.UseRoles({
    resource: "Software",
    action: "read",
    possession: "any",
  })
  async softwareItems(
    @graphql.Args() args: SoftwareFindManyArgs
  ): Promise<Software[]> {
    return this.service.softwareItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Software, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Software",
    action: "read",
    possession: "own",
  })
  async software(
    @graphql.Args() args: SoftwareFindUniqueArgs
  ): Promise<Software | null> {
    const result = await this.service.software(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Software)
  @nestAccessControl.UseRoles({
    resource: "Software",
    action: "delete",
    possession: "any",
  })
  async deleteSoftware(
    @graphql.Args() args: DeleteSoftwareArgs
  ): Promise<Software | null> {
    try {
      return await this.service.deleteSoftware(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
